Exec THEM_COURSES '8888001',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',3
Exec THEM_COURSES '8888002',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',153
Exec THEM_COURSES '8888003',N'Digital Marketing ','DMKT123456',N'Cung cấp kiến thức về tiếp thị số từ cơ bản đến chuyên sâu, bao gồm SEO, quảng cáo Google, quảng cáo trên mạng xã hội và email marketing. Bạn sẽ học cách tối ưu hóa chiến dịch quảng cáo trực tuyến để tiếp cận khách hàng mục tiêu và tăng trưởng doanh thu.',99
Exec THEM_COURSES '8888004',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',87
Exec THEM_COURSES '8888005',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',129
Exec THEM_COURSES '8888006',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',70
Exec THEM_COURSES '8888007',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',93
Exec THEM_COURSES '8888008',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',2
Exec THEM_COURSES '8888009',N' Phân Tích Dữ Liệu','PTDL123456',N'Khóa học giúp bạn hiểu cách thu thập, phân tích và trình bày dữ liệu một cách hiệu quả. Bạn sẽ nắm được các công cụ phân tích phổ biến như Excel, Python, và các kỹ thuật trực quan hóa dữ liệu để đưa ra quyết định chính xác dựa trên dữ liệu.',3
Exec THEM_COURSES '8888010',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',161
Exec THEM_COURSES '8888011',N' Phân Tích Dữ Liệu','PTDL123456',N'Khóa học giúp bạn hiểu cách thu thập, phân tích và trình bày dữ liệu một cách hiệu quả. Bạn sẽ nắm được các công cụ phân tích phổ biến như Excel, Python, và các kỹ thuật trực quan hóa dữ liệu để đưa ra quyết định chính xác dựa trên dữ liệu.',56
Exec THEM_COURSES '8888012',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',199
Exec THEM_COURSES '8888013',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',54
Exec THEM_COURSES '8888014',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',168
Exec THEM_COURSES '8888015',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',99
Exec THEM_COURSES '8888016',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',120
Exec THEM_COURSES '8888017',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',38
Exec THEM_COURSES '8888018',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',2
Exec THEM_COURSES '8888019',N'Digital Marketing ','DMKT123456',N'Cung cấp kiến thức về tiếp thị số từ cơ bản đến chuyên sâu, bao gồm SEO, quảng cáo Google, quảng cáo trên mạng xã hội và email marketing. Bạn sẽ học cách tối ưu hóa chiến dịch quảng cáo trực tuyến để tiếp cận khách hàng mục tiêu và tăng trưởng doanh thu.',190
Exec THEM_COURSES '8888020',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',190
Exec THEM_COURSES '8888021',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',153
Exec THEM_COURSES '8888022',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',10
Exec THEM_COURSES '8888023',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',39
Exec THEM_COURSES '8888024',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',39
Exec THEM_COURSES '8888025',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',61
Exec THEM_COURSES '8888026',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',186
Exec THEM_COURSES '8888027',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',120
Exec THEM_COURSES '8888028',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',116
Exec THEM_COURSES '8888029',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',112
Exec THEM_COURSES '8888030',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',68
Exec THEM_COURSES '8888031',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',146
Exec THEM_COURSES '8888032',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',94
Exec THEM_COURSES '8888033',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',146
Exec THEM_COURSES '8888034',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',93
Exec THEM_COURSES '8888035',N'Quản Lý Dự Án','QLDA123456',N'Cung cấp những kiến thức và kỹ năng cần thiết để quản lý dự án hiệu quả, từ lập kế hoạch, phân bổ tài nguyên đến giám sát tiến độ và đánh giá kết quả. Khóa học phù hợp cho những ai muốn nâng cao năng lực quản lý trong mọi lĩnh vực.',41
Exec THEM_COURSES '8888036',N'Quản Lý Dự Án','QLDA123456',N'Cung cấp những kiến thức và kỹ năng cần thiết để quản lý dự án hiệu quả, từ lập kế hoạch, phân bổ tài nguyên đến giám sát tiến độ và đánh giá kết quả. Khóa học phù hợp cho những ai muốn nâng cao năng lực quản lý trong mọi lĩnh vực.',54
Exec THEM_COURSES '8888037',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',129
Exec THEM_COURSES '8888038',N'Digital Marketing ','DMKT123456',N'Cung cấp kiến thức về tiếp thị số từ cơ bản đến chuyên sâu, bao gồm SEO, quảng cáo Google, quảng cáo trên mạng xã hội và email marketing. Bạn sẽ học cách tối ưu hóa chiến dịch quảng cáo trực tuyến để tiếp cận khách hàng mục tiêu và tăng trưởng doanh thu.',127
Exec THEM_COURSES '8888039',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',29
Exec THEM_COURSES '8888040',N'Digital Marketing ','DMKT123456',N'Cung cấp kiến thức về tiếp thị số từ cơ bản đến chuyên sâu, bao gồm SEO, quảng cáo Google, quảng cáo trên mạng xã hội và email marketing. Bạn sẽ học cách tối ưu hóa chiến dịch quảng cáo trực tuyến để tiếp cận khách hàng mục tiêu và tăng trưởng doanh thu.',41
Exec THEM_COURSES '8888041',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',125
Exec THEM_COURSES '8888042',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',52
Exec THEM_COURSES '8888043',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',39
Exec THEM_COURSES '8888044',N' Phân Tích Dữ Liệu','PTDL123456',N'Khóa học giúp bạn hiểu cách thu thập, phân tích và trình bày dữ liệu một cách hiệu quả. Bạn sẽ nắm được các công cụ phân tích phổ biến như Excel, Python, và các kỹ thuật trực quan hóa dữ liệu để đưa ra quyết định chính xác dựa trên dữ liệu.',186
Exec THEM_COURSES '8888045',N'Quản Lý Dự Án','QLDA123456',N'Cung cấp những kiến thức và kỹ năng cần thiết để quản lý dự án hiệu quả, từ lập kế hoạch, phân bổ tài nguyên đến giám sát tiến độ và đánh giá kết quả. Khóa học phù hợp cho những ai muốn nâng cao năng lực quản lý trong mọi lĩnh vực.',47
Exec THEM_COURSES '8888046',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',110
Exec THEM_COURSES '8888047',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',38
Exec THEM_COURSES '8888048',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',93
Exec THEM_COURSES '8888049',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',50
Exec THEM_COURSES '8888050',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',17
Exec THEM_COURSES '8888051',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',182
Exec THEM_COURSES '8888052',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',37
Exec THEM_COURSES '8888053',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',68
Exec THEM_COURSES '8888054',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',189
Exec THEM_COURSES '8888055',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',168
Exec THEM_COURSES '8888056',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',25
Exec THEM_COURSES '8888057',N'Quản Lý Dự Án','QLDA123456',N'Cung cấp những kiến thức và kỹ năng cần thiết để quản lý dự án hiệu quả, từ lập kế hoạch, phân bổ tài nguyên đến giám sát tiến độ và đánh giá kết quả. Khóa học phù hợp cho những ai muốn nâng cao năng lực quản lý trong mọi lĩnh vực.',10
Exec THEM_COURSES '8888058',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',168
Exec THEM_COURSES '8888059',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',128
Exec THEM_COURSES '8888060',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',90
Exec THEM_COURSES '8888061',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',2
Exec THEM_COURSES '8888062',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',52
Exec THEM_COURSES '8888063',N'Quản Lý Dự Án','QLDA123456',N'Cung cấp những kiến thức và kỹ năng cần thiết để quản lý dự án hiệu quả, từ lập kế hoạch, phân bổ tài nguyên đến giám sát tiến độ và đánh giá kết quả. Khóa học phù hợp cho những ai muốn nâng cao năng lực quản lý trong mọi lĩnh vực.',146
Exec THEM_COURSES '8888064',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',173
Exec THEM_COURSES '8888065',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',90
Exec THEM_COURSES '8888066',N' Phân Tích Dữ Liệu','PTDL123456',N'Khóa học giúp bạn hiểu cách thu thập, phân tích và trình bày dữ liệu một cách hiệu quả. Bạn sẽ nắm được các công cụ phân tích phổ biến như Excel, Python, và các kỹ thuật trực quan hóa dữ liệu để đưa ra quyết định chính xác dựa trên dữ liệu.',39
Exec THEM_COURSES '8888067',N'Quản Lý Dự Án','QLDA123456',N'Cung cấp những kiến thức và kỹ năng cần thiết để quản lý dự án hiệu quả, từ lập kế hoạch, phân bổ tài nguyên đến giám sát tiến độ và đánh giá kết quả. Khóa học phù hợp cho những ai muốn nâng cao năng lực quản lý trong mọi lĩnh vực.',144
Exec THEM_COURSES '8888068',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',94
Exec THEM_COURSES '8888069',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',99
Exec THEM_COURSES '8888070',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',27
Exec THEM_COURSES '8888071',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',198
Exec THEM_COURSES '8888072',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',70
Exec THEM_COURSES '8888073',N'Quản Lý Dự Án','QLDA123456',N'Cung cấp những kiến thức và kỹ năng cần thiết để quản lý dự án hiệu quả, từ lập kế hoạch, phân bổ tài nguyên đến giám sát tiến độ và đánh giá kết quả. Khóa học phù hợp cho những ai muốn nâng cao năng lực quản lý trong mọi lĩnh vực.',38
Exec THEM_COURSES '8888074',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',60
Exec THEM_COURSES '8888075',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',90
Exec THEM_COURSES '8888076',N'Digital Marketing ','DMKT123456',N'Cung cấp kiến thức về tiếp thị số từ cơ bản đến chuyên sâu, bao gồm SEO, quảng cáo Google, quảng cáo trên mạng xã hội và email marketing. Bạn sẽ học cách tối ưu hóa chiến dịch quảng cáo trực tuyến để tiếp cận khách hàng mục tiêu và tăng trưởng doanh thu.',68
Exec THEM_COURSES '8888077',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',87
Exec THEM_COURSES '8888078',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',128
Exec THEM_COURSES '8888079',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',94
Exec THEM_COURSES '8888080',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',25
Exec THEM_COURSES '8888081',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',189
Exec THEM_COURSES '8888082',N'Digital Marketing ','DMKT123456',N'Cung cấp kiến thức về tiếp thị số từ cơ bản đến chuyên sâu, bao gồm SEO, quảng cáo Google, quảng cáo trên mạng xã hội và email marketing. Bạn sẽ học cách tối ưu hóa chiến dịch quảng cáo trực tuyến để tiếp cận khách hàng mục tiêu và tăng trưởng doanh thu.',21
Exec THEM_COURSES '8888083',N'Quản Lý Dự Án','QLDA123456',N'Cung cấp những kiến thức và kỹ năng cần thiết để quản lý dự án hiệu quả, từ lập kế hoạch, phân bổ tài nguyên đến giám sát tiến độ và đánh giá kết quả. Khóa học phù hợp cho những ai muốn nâng cao năng lực quản lý trong mọi lĩnh vực.',94
Exec THEM_COURSES '8888084',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',22
Exec THEM_COURSES '8888085',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',56
Exec THEM_COURSES '8888086',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',26
Exec THEM_COURSES '8888087',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',198
Exec THEM_COURSES '8888088',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',29
Exec THEM_COURSES '8888089',N'Digital Marketing ','DMKT123456',N'Cung cấp kiến thức về tiếp thị số từ cơ bản đến chuyên sâu, bao gồm SEO, quảng cáo Google, quảng cáo trên mạng xã hội và email marketing. Bạn sẽ học cách tối ưu hóa chiến dịch quảng cáo trực tuyến để tiếp cận khách hàng mục tiêu và tăng trưởng doanh thu.',120
Exec THEM_COURSES '8888090',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',110
Exec THEM_COURSES '8888091',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',52
Exec THEM_COURSES '8888092',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',60
Exec THEM_COURSES '8888093',N' Phân Tích Dữ Liệu','PTDL123456',N'Khóa học giúp bạn hiểu cách thu thập, phân tích và trình bày dữ liệu một cách hiệu quả. Bạn sẽ nắm được các công cụ phân tích phổ biến như Excel, Python, và các kỹ thuật trực quan hóa dữ liệu để đưa ra quyết định chính xác dựa trên dữ liệu.',68
Exec THEM_COURSES '8888094',N'Quản Lý Dự Án','QLDA123456',N'Cung cấp những kiến thức và kỹ năng cần thiết để quản lý dự án hiệu quả, từ lập kế hoạch, phân bổ tài nguyên đến giám sát tiến độ và đánh giá kết quả. Khóa học phù hợp cho những ai muốn nâng cao năng lực quản lý trong mọi lĩnh vực.',128
Exec THEM_COURSES '8888095',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',3
Exec THEM_COURSES '8888096',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',132
Exec THEM_COURSES '8888097',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',161
Exec THEM_COURSES '8888098',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',63
Exec THEM_COURSES '8888099',N'Digital Marketing ','DMKT123456',N'Cung cấp kiến thức về tiếp thị số từ cơ bản đến chuyên sâu, bao gồm SEO, quảng cáo Google, quảng cáo trên mạng xã hội và email marketing. Bạn sẽ học cách tối ưu hóa chiến dịch quảng cáo trực tuyến để tiếp cận khách hàng mục tiêu và tăng trưởng doanh thu.',39
Exec THEM_COURSES '8888100',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',10
Exec THEM_COURSES '8888101',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',110
Exec THEM_COURSES '8888102',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',68
Exec THEM_COURSES '8888103',N'Quản Lý Dự Án','QLDA123456',N'Cung cấp những kiến thức và kỹ năng cần thiết để quản lý dự án hiệu quả, từ lập kế hoạch, phân bổ tài nguyên đến giám sát tiến độ và đánh giá kết quả. Khóa học phù hợp cho những ai muốn nâng cao năng lực quản lý trong mọi lĩnh vực.',198
Exec THEM_COURSES '8888104',N' Phân Tích Dữ Liệu','PTDL123456',N'Khóa học giúp bạn hiểu cách thu thập, phân tích và trình bày dữ liệu một cách hiệu quả. Bạn sẽ nắm được các công cụ phân tích phổ biến như Excel, Python, và các kỹ thuật trực quan hóa dữ liệu để đưa ra quyết định chính xác dựa trên dữ liệu.',63
Exec THEM_COURSES '8888105',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',26
Exec THEM_COURSES '8888106',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',116
Exec THEM_COURSES '8888107',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',128
Exec THEM_COURSES '8888108',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',125
Exec THEM_COURSES '8888109',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',99
Exec THEM_COURSES '8888110',N'Digital Marketing ','DMKT123456',N'Cung cấp kiến thức về tiếp thị số từ cơ bản đến chuyên sâu, bao gồm SEO, quảng cáo Google, quảng cáo trên mạng xã hội và email marketing. Bạn sẽ học cách tối ưu hóa chiến dịch quảng cáo trực tuyến để tiếp cận khách hàng mục tiêu và tăng trưởng doanh thu.',173
Exec THEM_COURSES '8888111',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',129
Exec THEM_COURSES '8888112',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',41
Exec THEM_COURSES '8888113',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',173
Exec THEM_COURSES '8888114',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',26
Exec THEM_COURSES '8888115',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',90
Exec THEM_COURSES '8888116',N'Digital Marketing ','DMKT123456',N'Cung cấp kiến thức về tiếp thị số từ cơ bản đến chuyên sâu, bao gồm SEO, quảng cáo Google, quảng cáo trên mạng xã hội và email marketing. Bạn sẽ học cách tối ưu hóa chiến dịch quảng cáo trực tuyến để tiếp cận khách hàng mục tiêu và tăng trưởng doanh thu.',60
Exec THEM_COURSES '8888117',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',93
Exec THEM_COURSES '8888118',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',155
Exec THEM_COURSES '8888119',N'Quản Lý Dự Án','QLDA123456',N'Cung cấp những kiến thức và kỹ năng cần thiết để quản lý dự án hiệu quả, từ lập kế hoạch, phân bổ tài nguyên đến giám sát tiến độ và đánh giá kết quả. Khóa học phù hợp cho những ai muốn nâng cao năng lực quản lý trong mọi lĩnh vực.',68
Exec THEM_COURSES '8888120',N' Phân Tích Dữ Liệu','PTDL123456',N'Khóa học giúp bạn hiểu cách thu thập, phân tích và trình bày dữ liệu một cách hiệu quả. Bạn sẽ nắm được các công cụ phân tích phổ biến như Excel, Python, và các kỹ thuật trực quan hóa dữ liệu để đưa ra quyết định chính xác dựa trên dữ liệu.',25
Exec THEM_COURSES '8888121',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',25
Exec THEM_COURSES '8888122',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',48
Exec THEM_COURSES '8888123',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',63
Exec THEM_COURSES '8888124',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',3
Exec THEM_COURSES '8888125',N'Quản Lý Dự Án','QLDA123456',N'Cung cấp những kiến thức và kỹ năng cần thiết để quản lý dự án hiệu quả, từ lập kế hoạch, phân bổ tài nguyên đến giám sát tiến độ và đánh giá kết quả. Khóa học phù hợp cho những ai muốn nâng cao năng lực quản lý trong mọi lĩnh vực.',155
Exec THEM_COURSES '8888126',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',190
Exec THEM_COURSES '8888127',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',50
Exec THEM_COURSES '8888128',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',47
Exec THEM_COURSES '8888129',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',21
Exec THEM_COURSES '8888130',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',54
Exec THEM_COURSES '8888131',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',125
Exec THEM_COURSES '8888132',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',22
Exec THEM_COURSES '8888133',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',153
Exec THEM_COURSES '8888134',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',1
Exec THEM_COURSES '8888135',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',75
Exec THEM_COURSES '8888136',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',101
Exec THEM_COURSES '8888137',N' Phân Tích Dữ Liệu','PTDL123456',N'Khóa học giúp bạn hiểu cách thu thập, phân tích và trình bày dữ liệu một cách hiệu quả. Bạn sẽ nắm được các công cụ phân tích phổ biến như Excel, Python, và các kỹ thuật trực quan hóa dữ liệu để đưa ra quyết định chính xác dựa trên dữ liệu.',101
Exec THEM_COURSES '8888138',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',112
Exec THEM_COURSES '8888139',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',3
Exec THEM_COURSES '8888140',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',26
Exec THEM_COURSES '8888141',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',173
Exec THEM_COURSES '8888142',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',189
Exec THEM_COURSES '8888143',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',70
Exec THEM_COURSES '8888144',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',48
Exec THEM_COURSES '8888145',N'Digital Marketing ','DMKT123456',N'Cung cấp kiến thức về tiếp thị số từ cơ bản đến chuyên sâu, bao gồm SEO, quảng cáo Google, quảng cáo trên mạng xã hội và email marketing. Bạn sẽ học cách tối ưu hóa chiến dịch quảng cáo trực tuyến để tiếp cận khách hàng mục tiêu và tăng trưởng doanh thu.',99
Exec THEM_COURSES '8888146',N'Digital Marketing ','DMKT123456',N'Cung cấp kiến thức về tiếp thị số từ cơ bản đến chuyên sâu, bao gồm SEO, quảng cáo Google, quảng cáo trên mạng xã hội và email marketing. Bạn sẽ học cách tối ưu hóa chiến dịch quảng cáo trực tuyến để tiếp cận khách hàng mục tiêu và tăng trưởng doanh thu.',21
Exec THEM_COURSES '8888147',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',61
Exec THEM_COURSES '8888148',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',63
Exec THEM_COURSES '8888149',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',39
Exec THEM_COURSES '8888150',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',3
Exec THEM_COURSES '8888151',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',168
Exec THEM_COURSES '8888152',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',144
Exec THEM_COURSES '8888153',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',10
Exec THEM_COURSES '8888154',N' Phân Tích Dữ Liệu','PTDL123456',N'Khóa học giúp bạn hiểu cách thu thập, phân tích và trình bày dữ liệu một cách hiệu quả. Bạn sẽ nắm được các công cụ phân tích phổ biến như Excel, Python, và các kỹ thuật trực quan hóa dữ liệu để đưa ra quyết định chính xác dựa trên dữ liệu.',190
Exec THEM_COURSES '8888155',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',101
Exec THEM_COURSES '8888156',N' Phân Tích Dữ Liệu','PTDL123456',N'Khóa học giúp bạn hiểu cách thu thập, phân tích và trình bày dữ liệu một cách hiệu quả. Bạn sẽ nắm được các công cụ phân tích phổ biến như Excel, Python, và các kỹ thuật trực quan hóa dữ liệu để đưa ra quyết định chính xác dựa trên dữ liệu.',61
Exec THEM_COURSES '8888157',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',182
Exec THEM_COURSES '8888158',N'Digital Marketing ','DMKT123456',N'Cung cấp kiến thức về tiếp thị số từ cơ bản đến chuyên sâu, bao gồm SEO, quảng cáo Google, quảng cáo trên mạng xã hội và email marketing. Bạn sẽ học cách tối ưu hóa chiến dịch quảng cáo trực tuyến để tiếp cận khách hàng mục tiêu và tăng trưởng doanh thu.',106
Exec THEM_COURSES '8888159',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',132
Exec THEM_COURSES '8888160',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',190
Exec THEM_COURSES '8888161',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',52
Exec THEM_COURSES '8888162',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',106
Exec THEM_COURSES '8888163',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',27
Exec THEM_COURSES '8888164',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',75
Exec THEM_COURSES '8888165',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',116
Exec THEM_COURSES '8888166',N'Thuyết Trình Pro','TTPRO12345',N'Khóa học này giúp bạn rèn luyện kỹ năng thuyết trình chuyên nghiệp, thu hút người nghe và tự tin truyền đạt ý tưởng. Bạn sẽ học cách xây dựng cấu trúc bài thuyết trình, làm chủ ngôn ngữ cơ thể và sử dụng công cụ hỗ trợ như PowerPoint để nâng cao hiệu quả.',106
Exec THEM_COURSES '8888167',N'Quản Lý Dự Án','QLDA123456',N'Cung cấp những kiến thức và kỹ năng cần thiết để quản lý dự án hiệu quả, từ lập kế hoạch, phân bổ tài nguyên đến giám sát tiến độ và đánh giá kết quả. Khóa học phù hợp cho những ai muốn nâng cao năng lực quản lý trong mọi lĩnh vực.',129
Exec THEM_COURSES '8888168',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',186
Exec THEM_COURSES '8888169',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',153
Exec THEM_COURSES '8888170',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',60
Exec THEM_COURSES '8888171',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',153
Exec THEM_COURSES '8888172',N'Quản Lý Dự Án','QLDA123456',N'Cung cấp những kiến thức và kỹ năng cần thiết để quản lý dự án hiệu quả, từ lập kế hoạch, phân bổ tài nguyên đến giám sát tiến độ và đánh giá kết quả. Khóa học phù hợp cho những ai muốn nâng cao năng lực quản lý trong mọi lĩnh vực.',125
Exec THEM_COURSES '8888173',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',155
Exec THEM_COURSES '8888174',N'Digital Marketing ','DMKT123456',N'Cung cấp kiến thức về tiếp thị số từ cơ bản đến chuyên sâu, bao gồm SEO, quảng cáo Google, quảng cáo trên mạng xã hội và email marketing. Bạn sẽ học cách tối ưu hóa chiến dịch quảng cáo trực tuyến để tiếp cận khách hàng mục tiêu và tăng trưởng doanh thu.',155
Exec THEM_COURSES '8888175',N'Quản Lý Dự Án','QLDA123456',N'Cung cấp những kiến thức và kỹ năng cần thiết để quản lý dự án hiệu quả, từ lập kế hoạch, phân bổ tài nguyên đến giám sát tiến độ và đánh giá kết quả. Khóa học phù hợp cho những ai muốn nâng cao năng lực quản lý trong mọi lĩnh vực.',17
Exec THEM_COURSES '8888176',N' Phân Tích Dữ Liệu','PTDL123456',N'Khóa học giúp bạn hiểu cách thu thập, phân tích và trình bày dữ liệu một cách hiệu quả. Bạn sẽ nắm được các công cụ phân tích phổ biến như Excel, Python, và các kỹ thuật trực quan hóa dữ liệu để đưa ra quyết định chính xác dựa trên dữ liệu.',48
Exec THEM_COURSES '8888177',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',116
Exec THEM_COURSES '8888178',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',1
Exec THEM_COURSES '8888179',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',173
Exec THEM_COURSES '8888180',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',121
Exec THEM_COURSES '8888181',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',75
Exec THEM_COURSES '8888182',N'Thiết Kế Photoshop','TKPS123456',N'Khóa học này giúp bạn thành thạo các công cụ thiết kế và chỉnh sửa ảnh chuyên nghiệp bằng Photoshop. Từ chỉnh sửa cơ bản đến thiết kế nâng cao, bạn sẽ học cách tạo ra các sản phẩm đồ họa ấn tượng phục vụ cho công việc hoặc sở thích cá nhân.',148
Exec THEM_COURSES '8888183',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',10
Exec THEM_COURSES '8888184',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',87
Exec THEM_COURSES '8888185',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',94
Exec THEM_COURSES '8888186',N' Phân Tích Dữ Liệu','PTDL123456',N'Khóa học giúp bạn hiểu cách thu thập, phân tích và trình bày dữ liệu một cách hiệu quả. Bạn sẽ nắm được các công cụ phân tích phổ biến như Excel, Python, và các kỹ thuật trực quan hóa dữ liệu để đưa ra quyết định chính xác dựa trên dữ liệu.',10
Exec THEM_COURSES '8888187',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',198
Exec THEM_COURSES '8888188',N'Lập Trình Robot','LTRO123456',N'Khóa học cung cấp kiến thức về lập trình robot, từ các nền tảng cơ bản đến nâng cao. Bạn sẽ học cách lập trình các robot tự động, robot di chuyển và tham gia các dự án thực tế để phát triển kỹ năng trong lĩnh vực công nghệ này.',10
Exec THEM_COURSES '8888189',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',146
Exec THEM_COURSES '8888190',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',112
Exec THEM_COURSES '8888191',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',50
Exec THEM_COURSES '8888192',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',17
Exec THEM_COURSES '8888193',N'Digital Marketing ','DMKT123456',N'Cung cấp kiến thức về tiếp thị số từ cơ bản đến chuyên sâu, bao gồm SEO, quảng cáo Google, quảng cáo trên mạng xã hội và email marketing. Bạn sẽ học cách tối ưu hóa chiến dịch quảng cáo trực tuyến để tiếp cận khách hàng mục tiêu và tăng trưởng doanh thu.',112
Exec THEM_COURSES '8888194',N'Digital Marketing ','DMKT123456',N'Cung cấp kiến thức về tiếp thị số từ cơ bản đến chuyên sâu, bao gồm SEO, quảng cáo Google, quảng cáo trên mạng xã hội và email marketing. Bạn sẽ học cách tối ưu hóa chiến dịch quảng cáo trực tuyến để tiếp cận khách hàng mục tiêu và tăng trưởng doanh thu.',128
Exec THEM_COURSES '8888195',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',190
Exec THEM_COURSES '8888196',N'Kinh Doanh Online','KDON123456',N'Khóa học này hướng dẫn bạn cách bắt đầu và vận hành một doanh nghiệp trực tuyến thành công. Từ việc chọn sản phẩm, xây dựng website bán hàng, cho đến chiến lược marketing và quản lý vận hành, khóa học giúp bạn tăng doanh số và mở rộng quy mô kinh doanh.',61
Exec THEM_COURSES '8888197',N'Tư Duy Sáng Tạo','TDSANG1234',N'Khóa học này giúp phát triển khả năng tư duy sáng tạo, khuyến khích sự đổi mới trong công việc và cuộc sống. Bạn sẽ học các kỹ thuật để kích thích trí tưởng tượng, tìm giải pháp cho các vấn đề và phát huy tối đa tiềm năng sáng tạo cá nhân.',186
Exec THEM_COURSES '8888198',N'Lập Trình Web','LTWEB12345',N'Khóa học lập trình web từ cơ bản đến nâng cao giúp bạn xây dựng các trang web chuyên nghiệp. Bạn sẽ học các ngôn ngữ phổ biến như HTML, CSS, JavaScript, và các framework hiện đại để phát triển giao diện web thân thiện, hấp dẫn.',125
Exec THEM_COURSES '8888199',N'Giao Tiếp Chuyên Nghiệp','GTCN123456',N'Khóa học này tập trung vào việc rèn luyện kỹ năng giao tiếp chuyên nghiệp trong môi trường công sở và kinh doanh. Bạn sẽ học cách lắng nghe, diễn đạt ý tưởng một cách rõ ràng, và xây dựng mối quan hệ bền vững với đồng nghiệp và đối tác.',21
Exec THEM_COURSES '8888200',N'Quản Lý Dự Án','QLDA123456',N'Cung cấp những kiến thức và kỹ năng cần thiết để quản lý dự án hiệu quả, từ lập kế hoạch, phân bổ tài nguyên đến giám sát tiến độ và đánh giá kết quả. Khóa học phù hợp cho những ai muốn nâng cao năng lực quản lý trong mọi lĩnh vực.',121
